import React from 'react';
import {
  AbsoluteFill,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  Easing,
  Img
} from 'remotion';

interface NewsVideoProps {
  title: string;
  date: string;
  news: {
    title: string;
    quote: string;
    url: string;
  }[];
  comment: string;
  imageIndex?: number; // 1-5
}

export const NewsVideo: React.FC<NewsVideoProps> = ({title, date, news, comment, imageIndex = 1}) => {
  const frame = useCurrentFrame();
  const {fps, durationInFrames} = useVideoConfig();

  // タイトルのアニメーション
  const titleOpacity = interpolate(frame, [0, 20], [0, 1], {
    extrapolateRight: 'clamp',
    easing: Easing.out(Easing.cubic)
  });

  // 日付のアニメーション
  const dateOpacity = interpolate(frame, [15, 30], [0, 1], {
    extrapolateRight: 'clamp'
  });

  // ひとみ画像のアニメーション（右からスライドイン）
  const hitomiX = interpolate(frame, [0, 30], [500, 0], {
    extrapolateRight: 'clamp',
    easing: Easing.out(Easing.cubic)
  });
  
  const hitomiOpacity = interpolate(frame, [0, 20], [0, 1], {
    extrapolateRight: 'clamp'
  });

  // ニュース項目のアニメーション
  const getNewsAnimation = (index: number) => {
    const startFrame = 40 + (index * 30);
    const progress = interpolate(frame, [startFrame, startFrame + 20], [0, 1], {
      extrapolateLeft: 'clamp',
      extrapolateRight: 'clamp'
    });
    return {
      opacity: progress,
      y: interpolate(progress, [0, 1], [40, 0])
    };
  };

  // ひとことのアニメーション（ニュース1つのみ）
  const commentStart = 60;
  const commentOpacity = interpolate(frame, [commentStart, commentStart + 25], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  });
  
  const commentY = interpolate(frame, [commentStart, commentStart + 25], [30, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  });

  // ハッシュタグのアニメーション
  const hashtagOpacity = interpolate(frame, [durationInFrames - 30, durationInFrames - 10], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  });

  return (
    <AbsoluteFill
      style={{
        background: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 50%, #ff9a9e 100%)',
        fontFamily: 'Arial, sans-serif',
        overflow: 'hidden',
      }}
    >
      {/* ひとみ画像（右側・サイズ縮小） */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          right: 0,
          bottom: 0,
          width: 500,
          opacity: hitomiOpacity,
          transform: `translateX(${hitomiX}px)`,
          background: 'linear-gradient(180deg, rgba(255,255,255,0.3) 0%, rgba(255,200,180,0.5) 100%)',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          padding: 30,
        }}
      >
        <div
          style={{
            width: 420,
            height: 600,
            borderRadius: 30,
            overflow: 'hidden',
            boxShadow: '0 25px 80px rgba(0, 0, 0, 0.25)',
            border: '6px solid #ffffff',
          }}
        >
          <Img
            src={require(`../public/hitomi${imageIndex}.png`)}
            style={{
              width: '100%',
              height: '100%',
              objectFit: 'cover',
              objectPosition: 'center',
            }}
          />
        </div>
        <p
          style={{
            textAlign: 'center',
            fontSize: 32,
            color: '#333333',
            margin: '20px 0 0 0',
            fontWeight: 'bold',
          }}
        >
          Generated by Hitomi 👠
        </p>
      </div>

      {/* 左側コンテンツ */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 530,
          bottom: 0,
          padding: '60px 50px',
        }}
      >
        {/* ヘッダー */}
        <div
          style={{
            opacity: titleOpacity,
          }}
        >
          <h1
            style={{
              fontSize: 72,
              fontWeight: 'bold',
              color: '#2d3436',
              margin: 0,
              display: 'flex',
              alignItems: 'center',
              gap: 15,
              textShadow: '2px 2px 4px rgba(255,255,255,0.8)',
            }}
          >
            🤖 {title}
          </h1>
          <p
            style={{
              fontSize: 36,
              color: '#636e72',
              margin: '12px 0 0 0',
              opacity: dateOpacity,
              fontWeight: '500',
            }}
          >
            {date}
          </p>
        </div>

        {/* ニュース項目（1つだけ表示） */}
        <div
          style={{
            marginTop: 60,
          }}
        >
          {(() => {
            // 最初のニュース1つだけ表示
            const item = news[0];
            const anim = getNewsAnimation(0);
            return (
              <div
                style={{
                  opacity: anim.opacity,
                  transform: `translateY(${anim.y}px)`,
                  marginBottom: 25,
                  paddingLeft: 25,
                  borderLeft: '6px solid #e17055',
                  background: 'rgba(255,255,255,0.7)',
                  padding: '15px 25px',
                  borderRadius: '0 15px 15px 0',
                }}
              >
                <h2
                  style={{
                    fontSize: 56,
                    fontWeight: 'bold',
                    color: '#2d3436',
                    margin: '0 0 8px 0',
                  }}
                >
                  ■ {item.title}
                </h2>
                <p
                  style={{
                    fontSize: 42,
                    color: '#636e72',
                    margin: '0 0 6px 0',
                    fontStyle: 'italic',
                    lineHeight: 1.4,
                  }}
                >
                  「{item.quote}」
                </p>
                <p
                  style={{
                    fontSize: 24,
                    color: '#b2bec3',
                    margin: 0,
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                  }}
                >
                  {item.url.length > 35 ? item.url.substring(0, 35) + '...' : item.url}
                </p>
              </div>
            );
          })()}

          {/* ひとこと */}
          <div
            style={{
              opacity: commentOpacity,
              transform: `translateY(${commentY}px)`,
              marginTop: 30,
              padding: '25px 35px',
              background: 'linear-gradient(135deg, #2d3436, #636e72)',
              borderRadius: 20,
              borderLeft: '8px solid #e17055',
            }}
          >
            <p
              style={{
                fontSize: 42,
                fontWeight: 'bold',
                color: '#e17055',
                margin: '0 0 12px 0',
              }}
            >
              💡 ひとこと
            </p>
            <p
              style={{
                fontSize: 42,
                color: '#ffffff',
                margin: 0,
                lineHeight: 1.5,
              }}
            >
              {comment}
            </p>
          </div>
        </div>

        {/* ハッシュタグ */}
        <div
          style={{
            position: 'absolute',
            bottom: 50,
            opacity: hashtagOpacity,
          }}
        >
          <p
            style={{
              fontSize: 32,
              color: '#2d3436',
              margin: 0,
              fontWeight: 'bold',
            }}
          >
            #AI #TechNews
          </p>
        </div>
      </div>
    </AbsoluteFill>
  );
};
